---
- name: Deploy OSPF Configuration
  hosts: ios
  gather_facts: false
  tasks:
  - name: OSPF Manager (deploy)
    ansible.builtin.include_role:
      name: network.ospf.run
    vars:
      actions:
        - name: deploy
      inventory_directory: ./
