---
- name: Update Juniper Junos managed nodes to use new ACLs
  hosts: junos
  gather_facts: false
  vars_files:
    - acls.yml
  tasks:
    - name: Juniper NETCONF configuration
      ansible.builtin.import_tasks: tasks/junos_netconf_enable.yml

    - name: Juniper Junos ACL configuration
      ansible.builtin.import_tasks: tasks/junos_acl_config.yml

    - name: Assert that ACLs were correctly configured
      ansible.builtin.import_tasks: tasks/junos_acl_verify.yml
