download_url: https://hub.lab.example.com/api/galaxy/v3/plugin/ansible/content/validated/collections/artifacts/network-base-2.0.0.tar.gz
format_version: 1.0.0
name: base
namespace: network
server: https://hub.lab.example.com/api/galaxy/content/validated/
signatures: []
version: 2.0.0
version_url: /api/galaxy/content/validated/v3/plugin/ansible/content/validated/collections/index/network/base/versions/2.0.0/
