---
- hosts: ios
  gather_facts: false
  tasks:
    - name: Network OSPF Manager
      ansible.builtin.include_role:
        name: network.ospf.run
      vars:
        actions:
          - name: health_check
            vars:
              details: true
              checks:
                - name: all_neighbors_up
                # - name: all_neighbors_down
                # - name: min_neighbors_up
                #   min_count: 1

          # - name: persist
