---
- name: Set default path
  ansible.builtin.set_fact:
    inventory_directory: ./inventory
  when: inventory_directory is not defined

- name: Get list of SOT files
  ansible.builtin.find:
    paths: "{{ inventory_directory }}/host_vars/{{ inventory_hostname }}"
    recurse: false
    patterns: "*.yaml"
    file_type: file
  register: found_directories

- name: Set default state as 'overridden'
  ansible.builtin.set_fact:
    state: 'overridden'
  when: state is not defined

- name: Include check_drift task
  ansible.builtin.include_tasks: includes/check_drift.yaml
  loop: "{{ found_directories.files }}"
  loop_control:
    loop_var: rms
  when:
    - resources is defined

- name: Detect drift
  ansible.builtin.debug:
    msg: "There is no configuration drift found"
