---
- name: Invoke gather function
  ansible.builtin.include_role:
    name: network.base.resource_manager
  vars:
    action: 'gather'
    resources:
      - 'ospfv2'
      - 'ospfv3'
      - 'ospf_interfaces'
