---
- name: Set default path
  ansible.builtin.set_fact:
    inventory: ./inventory
  when: inventory_directory is not defined

- name: Set default path
  ansible.builtin.set_fact:
    inventory: "{{ inventory_directory }}"
  when: inventory_directory is defined

- name: Invoke gather function
  ansible.builtin.include_role:
    name: network.base.resource_manager
  vars:
    action: 'persist'
    resources:
      - 'ospfv2'
      - 'ospfv3'
      - 'ospf_interfaces'
    inventory_directory: "{{ inventory }}"
