---
- name: Gather facts from Cisco IOS managed nodes
  hosts: ios
  gather_facts: false
  tasks:
    - name: Gather IOS facts
      cisco.ios.ios_facts:
        gather_subset:
          - all

- name: Gather facts from Arista EOS managed nodes
  hosts: eos
  gather_facts: false
  tasks:
    - name: Gather EOS facts
      arista.eos.eos_facts:
        gather_subset:
          - all

- name: Play to build a report
  hosts: workstation
  gather_facts: false
  tasks:
    - name: Build the report
      ansible.builtin.include_role:
        name: report
